In [1]:
import sys
sys.path.append('..')
import numpy as np
from common.layers import MatMul

In [10]:
# 샘플 맥락 데이터
c0 = np.array([[1,0,0,0,0,0,0]])
c1 = np.array([[1,0,0,0,0,0,0]])

W_in = np.random.randn(7,3)
W_out = np.random.randn(3,7)
print(W_in)
print(W_out)

in_layer0 = MatMul(W_in)
in_layer1 = MatMul(W_in)
out_layer = MatMul(W_out)

h0 = in_layer0.forward(c0)
print('h0:', h0)
h1 = in_layer1.forward(c1)
print('h1:', h1)
h = 0.5*(h0 + h1)
s = out_layer.forward(h)
print(s)

[[-0.38674897  1.696315   -1.83185896]
 [-1.35468706  1.19357777 -1.32357242]
 [-0.51954698 -0.70369394  0.15841229]
 [-2.34658835  0.84684349 -0.32611707]
 [ 1.36976082  0.04595625  0.23343973]
 [ 0.46476247 -0.28758718 -1.16643119]
 [ 0.66593273 -1.57158098  1.72638671]]
[[ 0.86687809  0.81770073 -0.46621184 -1.36379088  0.65665456  1.07419371
   1.3288486 ]
 [-1.21359033 -1.2134169  -0.28948444  1.32354784 -0.6109561  -0.56747759
   0.06519257]
 [-0.24125774  2.39647658 -0.36107545  0.38719934  0.19486027 -0.88863669
  -1.78144588]]
h0: [[-0.38674897  1.696315   -1.83185896]]
h1: [[-0.38674897  1.696315   -1.83185896]]
[[-1.95194553 -6.76458931  0.35068946  2.06330421 -1.64729101  0.24979302
   2.8600139 ]]


In [11]:
from common.util import preprocess
text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = preprocess(text)
print(corpus)
print(id_to_word)
print(word_to_id)

[0 1 2 3 4 1 5 6]
{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}
{'you': 0, 'say': 1, 'goodbye': 2, 'and': 3, 'i': 4, 'hello': 5, '.': 6}


In [12]:
def create_contexts_target(corpus, window_size=1):
    target = corpus[window_size:-window_size]
    contexts = []
    
    for idx in range(window_size, len(corpus)-window_size):
        cs = []
        for t in range(-window_size, window_size + 1):
            if t == 0:
                continue
            cs.append(corpus[idx + t])
        contexts.append(cs)
        
    return np.array(contexts), np.array(target)

In [13]:
contexts, target = create_contexts_target(corpus, window_size=1)

In [14]:
print(contexts)

[[0 2]
 [1 3]
 [2 4]
 [3 1]
 [4 5]
 [1 6]]


In [15]:
print(target)

[1 2 3 4 1 5]
