In [1]:
import sys
sys.path.append('..')
import numpy as np
from common.layers import MatMul

In [2]:
# 샘플 맥락 데이터
c0 = np.array([[1,0,0,0,0,0,0]])
c1 = np.array([[1,0,0,0,0,0,0]])

W_in = np.random.randn(7,3)
W_out = np.random.randn(3,7)
print(W_in)
print(W_out)

in_layer0 = MatMul(W_in)
in_layer1 = MatMul(W_in)
out_layer = MatMul(W_out)

h0 = in_layer0.forward(c0)
print('h0:', h0)
h1 = in_layer1.forward(c1)
print('h1:', h1)
h = 0.5*(h0 + h1)
s = out_layer.forward(h)
print(s)

[[-1.0224354   0.0593236  -0.23685318]
 [ 0.36997645 -0.7598329  -0.40977879]
 [-0.3879639   0.9016081   0.99655203]
 [ 2.01238382 -1.80793249  0.00296429]
 [ 1.02391734 -0.09967729  0.00580056]
 [ 0.65696389  1.71829522 -1.67258369]
 [-1.80027664  0.79823399  0.83520796]]
[[ 0.70080124 -0.87967137  0.38261737 -1.00648825  1.87406384  0.29094776
   0.79349256]
 [-1.09215895  1.04586757  0.46725146  0.63108838 -1.40844657 -0.69793743
  -1.37388189]
 [ 1.35989438  2.20176356  0.480928    0.55699124 -0.82882966  1.12954662
   0.58355938]]
h0: [[-1.0224354   0.0593236  -0.23685318]]
h1: [[-1.0224354   0.0593236  -0.23685318]]
[[-1.10341011  0.43995706 -0.47739184  0.9345825  -1.80335238 -0.60641616
  -1.0310164 ]]


In [3]:
from common.util import preprocess
text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = preprocess(text)
print(corpus)
print(id_to_word)
print(word_to_id)

[0 1 2 3 4 1 5 6]
{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}
{'you': 0, 'say': 1, 'goodbye': 2, 'and': 3, 'i': 4, 'hello': 5, '.': 6}


In [4]:
def create_contexts_target(corpus, window_size=1):
    target = corpus[window_size:-window_size]
    contexts = []
    
    for idx in range(window_size, len(corpus)-window_size):
        cs = []
        for t in range(-window_size, window_size + 1):
            if t == 0:
                continue
            cs.append(corpus[idx + t])
        contexts.append(cs)
        
    return np.array(contexts), np.array(target)

In [5]:
contexts, target = create_contexts_target(corpus, window_size=1)

In [6]:
print(contexts)

[[0 2]
 [1 3]
 [2 4]
 [3 1]
 [4 5]
 [1 6]]


In [7]:
print(target)

[1 2 3 4 1 5]


In [8]:
print(sys.version)

3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]
